name: checks
on:
  - push
  - pull_request
  - workflow_call
jobs:
  test:
    uses: adonisjs/core/.github/workflows/test.yml@main
    with:
      install-pnpm: true

  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@main
